### Create an user
POST http://localhost:3001/users
Content-Type: application/json

{
  "email": "strong-test@example.com",
  "password": "Password!123"
}

### Get current logged user
GET http://localhost:3001/users
Set-Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODlhNDgwMThlYzRmOTkxNTIwMDJjNGEiLCJpYXQiOjE3NTQ5NDE0NTEsImV4cCI6MTc1NDk0NTA1MX0.NGFrHPdIw7OJXIlqLhgZi6wYxuyOE9_tfbRzQropTlw; Path=/; Expires=Wed, 13 Aug 2025 03:17:20 GMT; HttpOnly