### Create an user
POST http://localhost:3001/users
Content-Type: application/json

{
  "email": "strong-test@example.com",
  "password": "Password!123"
}

### Get current logged user
GET http://localhost:3001/users
Set-Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk2Njc4NDQyNTU3ZGM1OTRjODNiNzciLCJpYXQiOjE3NTQ2ODg3NTAsImV4cCI6MTc1NDY5MjM1MH0.j48cU6bMXFurvxfZ73PFu_72i3DsZ8uIPqT9SSF3zoA; Path=/; Expires=Tue, 12 Aug 2025 09:52:00 GMT; HttpOnly